spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/testdb

#logging:
#  level:
#    root: INFO                # Default logging level for all packages
##    org.springframework.web: DEBUG  # Enable DEBUG logs for Spring Web package
##    com.yourpckg: TRACE     # Enable TRACE logs for your specific package
#    org.hibernate: WARN        # Set logging level for Hibernate to WARN
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"  # Customize log format for console output
#  file:
#    name: logs/application.log   # Log to a file
#  logback:
#    rollingpolicy:
#      max-history: 30
#      max-file-size: 10MB
#logging:
#  level:
#    org.springframework.data.mongodb.core.MongoTemplate: TRACE
#    org.mongodb.driver.protocol.command: DEBUG
#    org.springframework.data.mongodb.repository.query: DEBUG

mongock:
  change-logs-scan-package: ua.epam.mishchenko.ticketbooking.db.migration